baseURL = 'https://kohorte-mittellinie.eu/'
title = 'Kohorte Mittellinie'
author = "Marcel Schilling"
# paginate = 3
languageCode = "de"
DefaultContentLanguage = "de"
#enableInlineShortcodes = true
## prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
## See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
#ignoreErrors = ["error-remote-getjson"]

footnoteReturnLinkContents = "^"

# Theme specific examples
#author = "Marcel Schilling"
#copyright = "Marcel Schilling"
# googleAnalytics = "UA-123-45"
enableRobotsTXT = true
#pygmentsCodeFences = true
canonifyurls = true
#paginate = 6
theme = 'bootstrap-bp'

#[sitemap]
#    changefreq = "weekly"
#    priority = 0.5
#
#[permalinks]
#    posts = "/:year/:month/:slug/"
#    post = "/:year/:month/:slug/"
#    pages = "/:slug/"
#    page = "/:slug/"

[Author]  
  name = "Kohorte Mittellinie"

[params]
  description = "Inoffizieller Fanclub des 1. FC Union Berlin (nicht eingetragener Verein)"
  # showPostSummary = true
  # startPageColumns = true
  # showListsGrouped = true
   alwaysExpandMenu = true
  #customDateFormat = "02.01.2006"
   hideReadingTime = true
  themeColor="dark" # dark, light, blue, do not set for bootstrap default
  # js=["/js/test_site.js"]
  # css=["/css/test_site.css"]
  # csscdn=["https://fonts.googleapis.com/css?family=Concert+One|Roboto&display=swap"]

#[languages]
#  [languages.en]
#    languageName = "English"
#    #title = "Kohorte Mittellinie"
#    weight = 2
#    [languages.en.params]
#  [languages.de]
#    languageName = "Deutsch"
#    #title = "Kohorte Mittellinie"
#    weight = 1
#    [languages.de.params]


# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted.
# Code from https://themes.gohugo.io/future-imperfect/ theme
[social]
  # Coding Communities
  github           = "kohorte-mittellinie"
  # Social Networks
  facebook         = "groups/346133630560528"
  googleplus       = ""
  reddit           = ""
  quora            = ""
  youtube          = "" 
  vimeo            = ""
  whatsapp         = "" # WhatsApp Number
  instagram        = "kohorte_mittellinie"
  tumblr           = ""
  twitter          = ""
  skype            = ""
  snapchat         = ""
  pinterest        = ""
  telegram         = ""
  discord          = "" # invite link
  # Email
  email            = "admin@kohorte-mittellinie.eu"



[menu]

  [[menu.main]]
    identifier = "home"
    name = "Startseite"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "reports"
    name = "Berichte"
    url = "/reports/"
    weight = 20

  [[menu.main]]
    identifier = "agenda"
    name = "Termine"
    url = "/agenda/"
    weight = 30

  [[menu.footer]]
    identifier = "imprint"
    name = "Impressum"
    url = "/homepage/imprint/"
    weight = 10

  [[menu.footer]]
    identifier = "contact"
    name = "Kontakt"
    url = "/homepage/contact/"
    weight = 20

#  [[menu.footer]]
#    identifier = "categories"
#    name = "Categories"
#    url = "/categories/"
#    weight = 20
#
#  [[menu.footer]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags/"
#    weight = 30

[taxonomies]
  category = "categories"
  tag = "tags"
